project_id = "kfxnfovyblpzxfapvsob"

[functions.ai-chat]
verify_jwt = false

[functions.timetable-generate]
verify_jwt = false

[functions.task-difficulty]
verify_jwt = false

[functions.revision-plan]
verify_jwt = false

[functions.timetable-replan]
verify_jwt = false
